feat(op-node): pre-fetch receipts concurrently round 2
bnb-chain/opbnb pull request #104
Opened 2023-12-26 02:52 UTC by welkin22

### Description
I implemented the first version of concurrent code to pre-fetch receipts at https://github.com/bnb-chain/opbnb/pull/100, but there are some problems that need to be fixed. Our cache is an LRU cache with a maximum capacity of 1000 items. When the goroutine implementation is changed to concurrent, the maximum capacity is quickly reached. This leads to the following problems:
1. Since the cache is LRU, the Get method will insert data of old blocks that were about to be evicted into the front of the queue, causing a large amount of useless data to accumulate in the cache while useful data is pushed out.
2. Concurrency makes it very easy for the cache to become full, resulting in old block data being quickly evicted and the cache becoming ineffective.

### Rationale
I made some changes. In the pre-fetched goroutine, I removed the rateLimit and used waitGroup instead. I also added the `PreFetchReceipts` method, which indicates whether the cache has been filled. If it is filled, the pre-fetched goroutine will wait and retry.
At the same time, I modified the code in `FetchReceipts` to use the Peek method of the LRU cache instead of Get, because the Peek method does not change the order of the data in the cache. Additionally, I added a `PeekAndCleanOld` method, which clears all data in the cache that is older than the current request, ensuring that old data in the cache is promptly cleared. 
After making these changes, I completely abandoned the features of the LRU cache, but I still reused the LRU structure because its internal queue and map structures were still useful to me. I believe reusing the LRU structure should be enough to solve the problem.

### Example

none

### Changes

Notable changes:
* Changed the logic in `GoOrUpdatePreFetchReceipts`, using waitGroup instead of rateLimit.
* Added `PreFetchReceipts` method, replacing `FetchReceipts` in `GoOrUpdatePreFetchReceipts`.
* LRU cache has added the `Peek` and `PeekAndCleanOld` methods, as well as the `AddIfNotFull` method, to meet the needs of pre-fetch control caching.

2023-12-27 10:56 UTC, redhdx approved these changes

2023-12-28 01:25 UTC, Gemk83 approved these changes

2024-01-02 08:41 UTC, bendanzhentan approved these changes

2024-01-02 08:48 UTC, bendanzhentan requested changes
When `L2UnSafe.L1Origin - L2Safe.L1Origin > 1000`, this `receiptsCache will` cache block receipts in the range of `[L2Safe.L1Origin, L2Safe.L1Origin+1000)`, however, block receipts of `L2UnSafe.L1Origin` will not be cached. Could this result in the sequencer producing blocks more slowly? If yes, is this expectedly?

2024-01-02 09:00 UTC, welkin22 commented
> When `L2UnSafe.L1Origin - L2Safe.L1Origin > 1000`, this `receiptsCache will` cache block receipts in the range of `[L2Safe.L1Origin, L2Safe.L1Origin+1000)`, however, block receipts of `L2UnSafe.L1Origin` will not be cached. Could this result in the sequencer producing blocks more slowly? If yes, is this expectedly?

Yes, if the distance between unsafe and safe is too large, the cache cannot take care of both. This is unexpected, but 1000 blocks in our use case is equivalent to 50 minutes, and scenarios where the difference is 50 minutes are rare. If there is no better solution, I tend to temporarily ignore it.

2024-01-02 10:49 UTC, owen-reorg approved these changes

2024-01-02 11:30 UTC, bendanzhentan approved these changes

2024-01-02 11:31 UTC, merged